apiVersion: v1
kind: Service
metadata:
  labels:
    app: front-node-port
  name: km-front
spec:
  ports:
    - name:
      nodePort: 30000
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: kilometer-front
  type: NodePort
